### ISSUE TITLE
Cross-compile ES6

### ISSUE THREAD

**Issue by thomaswilburn** [seattletimes/newsapp-template#1]
We don't currently support running any compilation before we package up our AMD modules, but we .gitignored `tmp/`for a reason. We should add ES6 for the following items for sure:
- arrow functions
- spread and destructuring
- for-of

Eventually, we will switch over to ES6 modules (cross-compiling to AMD) with this as well.

All transpilation is dependent on making it fast. If development slows down when transpiling, we stick with ES5.

**Comment by jamiebuilds** [comment]
Hey @thomaswilburn, you might want to check out [6to5](6to5.github.io). There's a great [grunt plugin](https://github.com/sindresorhus/grunt-6to5) you can use, and there are [module formatters](http://6to5.github.io/modules.html) to compile to the module system of your choice. So there's no reason you can't start using ALL of es6 today! I'm a contributor for 6to5 so feel free to ping me for help, or you can join us on [gitter](https://gitter.im/6to5/6to5).

**Comment by thomaswilburn** [comment]
Thanks, I've actually been experimenting with 6to5 in our Browserify workflow on a few projects. I like it, but I'm not sure I'm going to integrate it at this time, since I'm still training our staff on our existing module systems. I'm also not sure I'm ready to go whole-hog with using it in our build code, and I think having mixed ES5/ES6 environments in the front and back end may be asking for trouble. It's a cool project, though, and I really like the output of it so far.

**Comment by jamiebuilds** [comment]
@thomaswilburn You can also use 6to5 in node via either [the cli](http://6to5.github.io/usage.html#node-2) or [require hook](http://6to5.github.io/usage.html#require-hook).

**Comment by thomaswilburn** [comment]
Yeah, I'm aware of the require hook and it wigs me out a little, to be honest. Also, will that work for templates that are run via Grunt's lo-dash templating? They don't typically get `require`'d, and 90% of our users are probably only interacting with the template through `grunt` and templating.

**Comment by jamiebuilds** [comment]
@thomaswilburn I'm going to look into if there's a way we can use 6to5 with lodash templates, thank you for bringing that up.

**Comment by thomaswilburn** [comment]
That would be great, thanks. To be honest, it's one of the places I really feel like ES6 is most helpful--at ArenaNet, one of our team members came up with a SweetJS macro to enable for-of loops in templates, and it simplified a lot of code. I'm not quite that hardcore when it comes to pre-parsing source files, so I haven't done it here, but it'd be great to have one canonical loop for collection values in our templates.

**Comment by thomaswilburn** [comment]
I'm going to close this, since we've been using 6to5 for a few projects now (thanks, @thejameskyle!). It's not something that we'll probably build in by default, but we've done it enough that I feel like I've got a good grasp on how to bring it in and use it successfully.
